<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[database is CONNECTED]]>
    </line>
    <line>
      <![CDATA[Test started]]>
    </line>
    <line>
      <![CDATA[database DISCONNECTED]]>
    </line>
  </reporter-output>
  <suite started-at="2022-12-06T00:00:20 IST" name="Default suite" finished-at="2022-12-06T00:00:51 IST" duration-ms="30498">
    <groups>
    </groups>
    <test started-at="2022-12-06T00:00:20 IST" name="Default test" finished-at="2022-12-06T00:00:51 IST" duration-ms="30498">
      <class name="com.actitime.testscripts._1_CreateCustomer">
        <test-method is-config="true" signature="databaseconnection()[pri:0, instance:com.actitime.testscripts._1_CreateCustomer@6a192cfe]" started-at="2022-12-06T00:00:20 IST" name="databaseconnection" finished-at="2022-12-06T00:00:20 IST" duration-ms="9" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[database is CONNECTED]]>
            </line>
          </reporter-output>
        </test-method> <!-- databaseconnection -->
        <test-method is-config="true" signature="launchbrowser()[pri:0, instance:com.actitime.testscripts._1_CreateCustomer@6a192cfe]" started-at="2022-12-06T00:00:20 IST" name="launchbrowser" finished-at="2022-12-06T00:00:23 IST" duration-ms="2853" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchbrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:com.actitime.testscripts._1_CreateCustomer@6a192cfe]" started-at="2022-12-06T00:00:23 IST" name="login" finished-at="2022-12-06T00:00:34 IST" duration-ms="10729" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="createCustomer()[pri:0, instance:com.actitime.testscripts._1_CreateCustomer@6a192cfe]" started-at="2022-12-06T00:00:34 IST" name="createCustomer" finished-at="2022-12-06T00:00:43 IST" duration-ms="8721" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.actitime.testscripts._1_CreateCustomer.createCustomer(_1_CreateCustomer.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test started]]>
            </line>
          </reporter-output>
        </test-method> <!-- createCustomer -->
        <test-method is-config="true" signature="logout()[pri:0, instance:com.actitime.testscripts._1_CreateCustomer@6a192cfe]" started-at="2022-12-06T00:00:43 IST" name="logout" finished-at="2022-12-06T00:00:51 IST" duration-ms="7666" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="closebrowser()[pri:0, instance:com.actitime.testscripts._1_CreateCustomer@6a192cfe]" started-at="2022-12-06T00:00:51 IST" name="closebrowser" finished-at="2022-12-06T00:00:51 IST" duration-ms="207" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrowser -->
        <test-method is-config="true" signature="databasedisconnection()[pri:0, instance:com.actitime.testscripts._1_CreateCustomer@6a192cfe]" started-at="2022-12-06T00:00:51 IST" name="databasedisconnection" finished-at="2022-12-06T00:00:51 IST" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[database DISCONNECTED]]>
            </line>
          </reporter-output>
        </test-method> <!-- databasedisconnection -->
      </class> <!-- com.actitime.testscripts._1_CreateCustomer -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
